### ISSUE TITLE
EQ crashes Rack

### ISSUE THREAD

**Issue by davephillips** [JerrySievert/CharredDesert#4] opened 2018-07-31 09:40 UTC
Fedora 23 Linux
VCV Rack 0.6.2

Loading EQ from latest git pull crashes Rack immediately.

make debug output has been posted to pastebin at https://pastebin.com/ifS6csJb

**Comment by ghost** [comment] 2018-07-31 20:26
same on windows.. (win 7 / VCV Rack 0.6.2) 

Loading EQ crashes Rack immediately.

**Comment by SteveRussell33** [comment] 2018-08-01 00:28
Likewise Win 10 VCV Rack 0.6.2

Loading EQ = insta-crash
Carbon doesn't appear in module selector
Carbon files in src/controller & src/view but no svg in /res

Oscar deprecated?

**Comment by JerrySievert** [comment] 2018-08-01 02:19
trying to reproduce.

**Comment by JerrySievert** [comment] 2018-08-01 02:21
and yeah, I made the decision to deprecate Oscar in favor of Oscar^2 - it's easy to emulate the behavior by not turning any knobs but wave selection in Oscar^2

**Comment by fractalgee** [comment] 2018-08-01 07:20
it does NOT crash on Mac OS X 10.11.6, just for completeness

**Comment by dizzisound** [comment] 2018-08-01 15:34
@JerrySievert Hi Jerry, it looks like the issue originates from a null pointer, in the override of the `draw `member of the _EqTypeDisplay_ widget. 
Just commenting out the residual code **line 493**: 
`nvgText(vg, box.pos.x + 1, box.pos.y + 1, text, NULL); `
and possibly the related uninitialized declaration at line 455:
`char *text;`
in the _deps/rack-components/display.hpp_ file should solve the issue.

I tested the fix after building the latest sources on a Windows 8.1 x64 machine.
I hope it could definitely solve the issue on all platforms, anyway.

In the meanwhile, thanks for your modules!
Best

**Comment by davephillips** [comment] 2018-08-01 19:52
@dizzisound Nice detective work ! Your suggested fix seems to be working here on Fedora 23 Linux, though I haven't had time to test its audio processing. But it's not crashing Rack 0.6.2 now. :)

**Comment by SteveRussell33** [comment] 2018-08-02 13:39
Tested dizzisound's fix with Win 10 VCV 0.6.2
Confirmed EQ loads without crash and seems to be processing correctly VCO->EQ->Scope

**Comment by EdwardRosenfeld** [comment] 2018-08-02 16:59
Where is this fix? I tried the latest on the download page and got the same results

Thanks, Eddie 

    On Thursday, August 2, 2018, 9:39:55 AM EDT, SteveRussell33 <notifications@github.com> wrote:  
 
 
Tested dizzisound's fix with Win 10 VCV 0.6.2
Confirmed EQ loads without crash and seems to be processing correctly VCO->EQ->Scope

**Comment by JerrySievert** [comment] 2018-08-02 17:08
I verified @dizzisound's finding and updated `rack-components`, I have not asked to have the plugin updated in vcv rack yet, I am considering quickly adding another module before release.

**Comment by EdwardRosenfeld** [comment] 2018-08-02 17:14
Thank you for this information, Jerry...I eagerly await the download of the new and improved plugins...

**Comment by JerrySievert** [comment] 2018-08-03 23:34
waiting for it to be released by the vcv team.

will close this once it is live.

also, fixed charcoal to be available, and added a mixer (that's why this release was delayed).  another new mixer with full cv control of everything coming soon.

**Comment by JerrySievert** [comment] 2018-08-06 20:16
this finally went live - going to close this.

btw, I ended up sneaking in a few more modules than expected, since it took so long to release:

* mixer - clean 8 channel mixer
* mixer cv - just like the 8 channel mixer, but with a ton of cv control
* cv - a simple half-module (x2) that gives you quick cv controls
* m - a micro half-module (x2) 2 channel mixer

**Closed as completed by JerrySievert** 2018-08-06 20:16 UTC
