### ISSUE TITLE
Oscar2 doesn't show shape in displays

### ISSUE THREAD

**Issue by SteveRussell33** [JerrySievert/CharredDesert#13] opened 2019-07-03 11:23 UTC
![oscar2](https://user-images.githubusercontent.com/41975381/60587834-53007800-9d8d-11e9-9d69-3f71cd5b61c8.png)
Win 10 Rack 1.1.1 dev

**Comment by JerrySievert** [comment] 2019-07-11 00:41
odd, ok, I'm going to do an update soon anyways, and will take a look.  what os are you using?

**Comment by JerrySievert** [comment] 2019-07-11 03:08
found the issue, will try to get a new release out in a couple of days (I'll submit it for update tonight)

going to leave this open until the issue is resolved.

**Comment by SteveRussell33** [comment] 2019-07-11 11:38
Looking good here @ https://github.com/JerrySievert/CharredDesert/commit/de1d5402675089ab8651734ba0a14fddcff5d1ab

![oscar2](https://user-images.githubusercontent.com/41975381/61056437-457d6a80-a3eb-11e9-9769-425aa94dd701.png)

**Comment by JerrySievert** [comment] 2019-07-13 15:15
and released, so going to go ahead and close this.

**Closed as completed by JerrySievert** 2019-07-13 15:15 UTC
